---
AllCops:
  DisplayCopNames: true
  Exclude:
    - "bin/**"
    - "db/schema.rb"
    - "db/**/schema.rb"
    - "db/**/cable_schema.rb"
    - "db/**/cache_schema.rb"
    - "db/**/queue_schema.rb"
    - "db/migrate/**"
    - "vendor/**/*"
    - "node_modules/**/*"
    - "tmp/**/*"
    - "log/**/*"
    - "public/**/*"
    - "storage/**/*"
  NewCops: enable
  TargetRailsVersion: 8.1
  TargetRubyVersion: 3.4
  SuggestExtensions: false

Layout/LineLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Rails:
  Enabled: true

Rails/UniqueValidationWithoutIndex:
  Enabled: false

plugins:
  - rubocop-performance
  - rubocop-rails

Style/AsciiComments:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

# Style/StringLiterals:
#   EnforcedStyle: double_quotes
#   Enabled: true

Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: always

Layout/EmptyLineAfterMagicComment:
  Enabled: true
  