# .slim-lint.yml
exclude:
  - 'vendor/**/*'
  - 'node_modules/**/*'
  - 'public/**/*'
  - 'tmp/**/*'
  - 'log/**/*'

linters:
  # Tag case check
  TagCase:
    enabled: false

  # Quote consistency
  QuoteConsistency:
    enabled: true

  # Empty lines check
  EmptyLines:
    enabled: true

  # Line length check
  LineLength:
    enabled: true
    max: 120

  # RuboCop integration
  RuboCop:
    enabled: true
    ignored_cops:
      - Layout/LineLength
      - Style/StringLiterals
      - Style/FrozenStringLiteralComment
      - Metrics/BlockLength

  # Trailing whitespace check
  TrailingWhitespace:
    enabled: true

  # Empty control statements
  EmptyControlStatement:
    enabled: true

  # Consecutive control statements
  ConsecutiveControlStatements:
    enabled: true
    max_consecutive: 2

  # Instance variables
  InstanceVariables:
    enabled: true
    exclude:
      - 'app/views/layouts/**/*'

  # Tag attributes
  TagAttribute:
    enabled: true

  # Control statement spacing
  ControlStatementSpacing:
    enabled: true

  # Redundant div
  RedundantDiv:
    enabled: false

  # Tab check
  Tab:
    enabled: true

  # Zero-width spaces
  Zwsp:
    enabled: true

  # Embedded engines
  EmbeddedEngines:
    enabled: true

  # Tag check
  Tag:
    enabled: true

  # Comment control statement (вместо Comment)
  CommentControlStatement:
    enabled: true

  # Trailing blank lines
  TrailingBlankLines:
    enabled: true

  # File length
  FileLength:
    enabled: false

  # Strict locals missing
  StrictLocalsMissing:
    enabled: false
    