# .slim-lint.yml
exclude:
  - 'vendor/**/*'
  - 'node_modules/**/*'
  - 'public/**/*'
  - 'tmp/**/*'
  - 'log/**/*'

linters:
  TagCase:
    enabled: true
  RuboCop:
    enabled: false
  InstanceVariables:
    enabled: false
  QuoteConsistency:
    enabled: false
  TrailingWhitespace:
    enabled: false
  TrailingBlankLines:
    enabled: false
  EmptyLines:
    enabled: false
  LineLength:
    enabled: false
  EmptyControlStatement:
    enabled: false
  ConsecutiveControlStatements:
    enabled: false
  TagAttribute:
    enabled: false
  ControlStatementSpacing:
    enabled: false
  RedundantDiv:
    enabled: false
  Tab:
    enabled: false
  Zwsp:
    enabled: false
  EmbeddedEngines:
    enabled: false
  Tag:
    enabled: false
  CommentControlStatement:
    enabled: false
  FileLength:
    enabled: false
  StrictLocalsMissing:
    enabled: false
